[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PATCH, OPTIONS"

# Scheduled daily digest at 08:00 ET (12:00 UTC)
[[scheduled]]
  path = "/.netlify/functions/overdueDigest"
  schedule = "0 12 * * *"